kumuluzee:
  name: scheduler-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/SchedulerDS
      connection-url: jdbc:postgresql://pg-scheduler:5432/scheduler
      username: dbuser
      password: postgres

rest-properties:
  maintenance-mode: false
  broken: false

