INSERT INTO section_name (name) VALUES ('Morning routine');
INSERT INTO section_name (name) VALUES ('9am-12am');
INSERT INTO section_name (name) VALUES ('Lunchtime');
INSERT INTO section_name (name) VALUES ('2pm-5pm');
INSERT INTO section_name (name) VALUES ('6pm-8pm');
INSERT INTO section_name (name) VALUES ('Evening routine');
INSERT INTO weekly_name (name) VALUES ('RSO lecture');
INSERT INTO weekly_name (name) VALUES ('RSO labs');
INSERT INTO weekly_name (name) VALUES ('Visit family');
INSERT INTO weekly_name (name) VALUES ('Do laundry');
INSERT INTO weekly_name (name) VALUES ('Work on project');
